self.addEventListener('install',e=>{
  e.waitUntil(
    caches.open('modoCine').then(c=>c.addAll([
      '/','/index.html','/login.html','/style.css','/script.js','/login.js'
    ]))
  );
});
self.addEventListener('fetch',e=>{
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});
